version: '3.1'
services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.33-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-list
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-database-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - mysql_db
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
      
  todo_list:
    container_name: 'todo_list'
    build:
      context: ./
    volumes:
      - .:/home/node/server
    depends_on:
      - mysql_db
    ports:
      - 3001:3001

volumes:
  mysql-database-data:
