version: '3.1'
services:
  MYSQL_DATABASE:
    image: mysql:8.0.33-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-list
    ports:
      - 3306:3306 
    volumes:
      - mysql-database-data:/var/lib/mysql

volumes:
  mysql-database-data: